var t = 0; //Time
var A = 0.9; //Amplitude
var b = 0.3; // Damping constant
// var b = 1;
// var m = 3; //Mass of block 
var m = 10;
var phase = 0 //Phase of system
var w = 1; //Angular Frequency

var ampSpan = document.getElementById("A_data");
var BSpan = document.getElementById("B_data");
var massSpan = document.getElementById("m_data");
var freqSpan = document.getElementById("w_data");
var phiSpan = document.getElementById("phi_data");
ampSpan.innerHTML = A;
BSpan.innerHTML = b;
massSpan.innerHTML = m;
freqSpan.innerHTML = w;
phiSpan.innerHTML = phase;